config/routes.rb
Pinteresting::Application.routes.draw do
  resources :pins

  devise_for :users
  root "pins#index"
  get "login" =>"pages#login"
  get "contact" =>"pages#contact"

  resources :pins do 
    member do 
      post :upvote
      post :downvote
    end
  end

end

app/models/pin.rb
class Pin < ActiveRecord::Base
  belongs_to :user
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }

  acts_as_votable

  validates :description, presence: true, length: { maximum: 256 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :pins

  validates :name, presence: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 # Prevent CSRF attacks by raising an exception.
 # For APIs, you may want to use :null_session instead.
 protect_from_forgery with: :exception
 before_filter :configure_permitted_parameters, if: :devise_controller?

protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) << :name
   devise_parameter_sanitizer.for(:account_update) << :name
 end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def about
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

 def index
   @pins = Pin.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 20)
 end

  def show
    @pin = Pin.find params[:id]
    @prev = Pin.where("id < #{@pin.id}").order(:id => :desc).first
    @next = Pin.where("id > #{@pin.id}").order(:id => :asc).first
  end

  def new
    @pin = current_user.pins.build
  end

  def edit
  end

  def upvote
    @pin = Pin.find params[:id]
    @pin.liked_by current_user
    redirect_to pin_path(@pin)
  end

  def downvote
    @pin = Pin.find params[:id]
    @pin.downvote_from current_user
    redirect_to pin_path(@pin)
  end

  def create
    @pin = current_user.pins.build(pin_params)
    respond_to do |format|
      if @pin.save
        ImageCreator.create(@pin) unless params[:pin]['image']
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pin }
      else
        format.html { render action: 'new' }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "TaSoeur.Fr", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Contacter ta Soeur", contact_path %></li>
      <% if user_signed_in? %>
        <li>
            <%= link_to new_pin_path do %>
              <span class="glyphicon glyphicon-plus"></span> New Pin
            <% end %>
        </li>
      <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
      <li><%= link_to "Réglages", edit_user_registration_path %></li>
      <% else %>
        <li><%= link_to "Login", new_user_session_path %></li>
      <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ta Soeur [Point] FR</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=287078058113113";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |name, msg| %>
     <%= content_tag(:div, msg, class: "alert alert-info") %>
		<% end %>
		<%= yield %>
	</div>
</body>
</html>

app/views/pages/_home.html.erb
<div class="jumbotron center">
	<h1>Ta soeur {point} Fr</h1>
	<h3>Tout le monde rêve de se la faire</h3>
		<p>
			<%= link_to "Vote pour ta soeur", new_user_session_path, class: "btn btn-default btn-lg" %>
			<%= link_to "Soumets ta soeur", new_user_registration_path, class: "btn btn-primary btn-lg" %>
		</p>
</div>

app/views/pages/about.html.erb
<h1>About</h1>
<p>This is a test</p>

app/views/pages/contact.html.erb
<div class="jumbotron center">
	<h1>Contacter ta soeur</h1>
	<h3>Plusieurs possibilités</h3>
		<p>
			<%= link_to "Regarde sous les grosses pierres", new_user_session_path, class: "btn btn-default btn-lg" %>
			<%= link_to "nique@tasoeur.fr", new_user_registration_path, class: "btn btn-primary btn-lg" %>
		</p>
</div>

app/views/pages/home.html.erb
<div class="jumbotron center">
	<h1>Ta soeur {point} Fr</h1>
	<h3>Tout le monde rêve de se la faire</h3>
	<% if user_signed_in? %>
		# do something
	<% else %>
		<p>
			<%= link_to "Vote pour ta soeur", new_user_session_path, class: "btn btn-default btn-lg" %>
			<%= link_to "Soumets ta soeur", new_user_registration_path, class: "btn btn-primary btn-lg" %>
		</p>
	<% end %>
</div>

app/views/pins/_form.html.erb
<%= form_for @pin, html: { multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/_tasoeur_vgt.html.erb
<html>
  <head>
    <meta charset="utf-8">
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  </head>
  <body style="margin:0!important;">
    <table cellpadding="0" cellspacing="0" border="0" width="500px" class="responsive-webinar">
      <tr>
        <td>
          <table width="500px" height="500px" border="0" cellspacing="0" cellpadding="30" align="center">
            <tr>
              <td bgcolor="#<%=["1abc9c", "2ecc71", "3498db", "9b59b6", "34495e", "f39c12", "e67e22", "c0392b", "bdc3c7", "7f8c8d" ].sample%>" align="left">
                <span style="font-size: 35px; font-family: Lato, Helvetica, Arial, sans-serif; font-weight: normal; color: #ffffff; text-decoration: none;"><%= pin.description %>
              </span>
              <span style="font-size: 18px; font-family: Lato, Helvetica, Arial, sans-serif; font-weight: normal; color: #fff; text-decoration: none;"><br />from TaSoeur.fr, with love.
              </span>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<%= render 'pages/home' unless user_signed_in? %>
  <div id="pins" class="transitions-enabled">
    <% @pins.each do |pin| %>
      <div class="box panel panel-default">
        <%= link_to image_tag(pin.image.url(:medium)), pin %>
        <div class="panel-body">
          <%= pin.description %><br/>
          <% if pin.user == current_user %>
            <div class="actions">
              <%= link_to edit_pin_path(pin) do %>
                <span class="glyphicon glyphicon-edit"></span>
                Edit
              <% end %>
              <%= link_to pin, method: :delete, data: { confirm: 'Mais tu es pas fou?' } do %>
                <span class="glyphicon glyphicon-trash"></span>
                Delete
              <% end %>
            </div>
          <% end %>
            <div class="votable">
              <span class="glyphicon glyphicon-circle-arrow-up"></span>
              <%= pin.upvotes.size %>
              <span class="glyphicon glyphicon-circle-arrow-down"></span>
            </div>
        </div>
      </div>
    <% end %>
  </div>
<div class="center">
   <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
</div>

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<% if @prev %>
<div <% if @next %>style="float:left;"<% end %>>
  <span class="glyphicon glyphicon-circle-arrow-left"></span>
  <%= link_to 'Précédent', pin_path(@prev), id: "prev-pin"%>
</div>
<% end %>
<% if @next %>
<div class="text-right">
  <%= link_to 'Suivant', pin_path(@next), id: "next-pin" %>
  <span class="glyphicon glyphicon-circle-arrow-right"></span>
</div>
<% end %>
<div class="row">
  <div class="col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-body center">
        <h2><%= @pin.description %></h2>
      </div>
      <div class="panel-heading center">
        <%= image_tag @pin.image.url(:medium) %>
      </div>
      <div class="panel-body">
        <p>Paroles de sagesses par <strong><%= @pin.user.name if @pin.user %> </strong>
        <%= link_to edit_pin_path(@pin) do %>
          <span class="glyphicon glyphicon-edit"></span>
          Edit
        <% end %>
        </p>
        <div class="fb-like" data-href="http://tasoeur.fr" data-layout="standard" data-action="like" data-show-faces="true" data-share="true"></div>
      </div>
    </div>
    <div class="panel panel-body center">
      <h3>Vote pour ta soeur</h3>
        <span class="glyphicon glyphicon-circle-arrow-up"></span>
        <%= link_to 'Elle prend cher', upvote_pin_path(@pin), method: :post %> (<%= @pin.upvotes.size %>) 
        <%= link_to 'Nique sa mère', downvote_pin_path(@pin), method: :post %> (<%= @pin.downvotes.size %>) 
        <span class="glyphicon glyphicon-circle-arrow-down"></span>
    </div>
    <div class="fb-comments" width="720px" data-href="http://tasoeur.fr/" data-numposts="10" data-colorscheme="light"></div>
</div>